// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4F33o4ATR3aCb0RSO8XIh8ESYMvFpjt8',
    appId: '1:658052071773:web:6e974cf27fa0b2589e68b4',
    messagingSenderId: '658052071773',
    projectId: 'chat-app-8dae9',
    authDomain: 'chat-app-8dae9.firebaseapp.com',
    storageBucket: 'chat-app-8dae9.appspot.com',
    measurementId: 'G-E1QX12PNHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVhGh4BJi6sJysr_l7HMCwKpb8irH5N8',
    appId: '1:658052071773:android:427e9946a1285f459e68b4',
    messagingSenderId: '658052071773',
    projectId: 'chat-app-8dae9',
    storageBucket: 'chat-app-8dae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdbYOjNVhBacDtrhJ5lGfrGGtPW6rxVs',
    appId: '1:658052071773:ios:833ea914a844817c9e68b4',
    messagingSenderId: '658052071773',
    projectId: 'chat-app-8dae9',
    storageBucket: 'chat-app-8dae9.appspot.com',
    iosClientId: '658052071773-p0s335p2aasar7o2qnmsr8ejm6dbc26j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjdbYOjNVhBacDtrhJ5lGfrGGtPW6rxVs',
    appId: '1:658052071773:ios:833ea914a844817c9e68b4',
    messagingSenderId: '658052071773',
    projectId: 'chat-app-8dae9',
    storageBucket: 'chat-app-8dae9.appspot.com',
    iosClientId: '658052071773-p0s335p2aasar7o2qnmsr8ejm6dbc26j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
